# Generated by Django 5.2.8 on 2026-02-14 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cible', models.CharField(choices=[('specifique', 'Utilisateur Spécifique'), ('role_chauffeur', 'Tous les Chauffeurs'), ('role_client', 'Tous les Clients'), ('tous', 'Tous les Utilisateurs')], max_length=20)),
                ('destinataire_email', models.EmailField(blank=True, help_text="Requis si cible est 'specifique'", max_length=254, null=True)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
