# Generated by Django 5.2.8 on 2026-02-13 17:26

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', authentication.models.UtilisateurManager()),
            ],
        ),
    ]
